### ISSUE TITLE
Error in IntronicExpressionReadBlock

### ISSUE THREAD

**Issue by komalsrathi** [francois-a/rnaseqc#1]
Hi,

I am using RNA-SeQC like this:

```
$ java -Xmx6g -jar RNA-SeQC_v1.1.8.jar \
-s PPTC-AF03-XTP1-A-1-0-R_sample_file.txt \
-t Homo_sapiens.GRCh37.71.hap.ERCC.gtf \
-r Homo_sapiens.GRCh37.71.hap.ERCC.sm.fa \
-o PPTC-AF03-XTP1-A-1-0-R
```

Java version
```
java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (Zulu 8.20.0.5-linux64) (build 1.8.0_121-b15)
OpenJDK 64-Bit Server VM (Zulu 8.20.0.5-linux64) (build 25.121-b15, mixed mode)
```

Here is the log with the error:

```
RNA-SeQC v1.1.8.1 07/11/14
Creating rRNA Interval List based on given GTF annotations
Retriving contig names from reference
	 contig names in reference: 185
Loading GTF for Read Counting
Converting to refGene
Transcript objects to RefGen format:	6 s
Running IntronicExpressionReadBlock Walker ....
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:146)
	at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:53)
	at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:55)
	at org.broadinstitute.cga.rnaseq.gatk.GATKTools.runIntronReadCount(GATKTools.java:216)
	at org.broadinstitute.cga.rnaseq.ReadCountMetrics.runRegionCounting(ReadCountMetrics.java:244)
	at org.broadinstitute.cga.rnaseq.ReadCountMetrics.runReadCountMetrics(ReadCountMetrics.java:59)
	at org.broadinstitute.cga.rnaseq.RNASeqMetrics.runMetrics(RNASeqMetrics.java:225)
	at org.broadinstitute.cga.rnaseq.RNASeqMetrics.execute(RNASeqMetrics.java:171)
	at org.broadinstitute.cga.rnaseq.RNASeqMetrics.main(RNASeqMetrics.java:139)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: could not create class file from ArrayBufferView.class
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:91)
	at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:79)
	... 9 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: could not create class file from ArrayBufferView.class
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.reflections.Reflections.scan(Reflections.java:162)
	... 11 more
Caused by: java.lang.RuntimeException: could not create class file from ArrayBufferView.class
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:41)
	at org.reflections.Reflections$2.run(Reflections.java:149)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: invalid constant type: 15
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1023)
	at javassist.bytecode.ConstPool.read(ConstPool.java:966)
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:127)
	at javassist.bytecode.ClassFile.read(ClassFile.java:693)
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:85)
	at org.reflections.adapters.JavassistAdapter.createClassObject(JavassistAdapter.java:86)
	at org.reflections.adapters.JavassistAdapter.createClassObject(JavassistAdapter.java:22)
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:38)
	... 6 more
```

Any help would be much appreciated.

**Comment by francois-a** [comment]
RNA-SeQC requires Java 1.7 (added to README).

**Comment by komalsrathi** [comment]
Thanks - it seems to be working.
